title: Otevřená města
lang: cs
twitter:
facebook: https://www.facebook.com/otevrenamesta
gitlab: https://gitlab.com/otevrenamesta
github: https://github.com/otevrenamesta
instagram:
cdn: /cdn/
menu:
  - label: O nás
    link: /o-nas/
  - label: Spolupráce
    link: /spoluprace
  - label: Projekty
    link: /projekty
  - label: Aktuality
    link: /clanky
  - label: Kontakt
    link: /kontakt
globalComponents:
  - paginator
detailpages:
  - path: /clanky/:id
    component: ./components/detailPages/post.js
  - path: /projekty/:id
    component: ./components/detailPages/project.js
    # children:
    #   - component: chci
    #     link: /
  - path: /clanky
    component: ./components/listPages/posts.js
  - path: /projekty
    component: ./components/listPages/projects.js